name: Lint CSS

on:
  push:
    branches: [ paulina ]
  pull_request:
    branches: [ paulina ]

jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Linter de CSS
        run: |
          npm init -y
          npm install --save-dev stylelint stylelint-config-standard

      - name: Validar CSS
        run: npx stylelint "**/*.css"