name: Lint CSS

on:
  push:
    branches:
      - paulina

jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar y Ejecutar Stylelint
        run: |
          npm install stylelint stylelint-config-standard --save-dev
          npx stylelint "**/*.css"